<?php

namespace ContainerOYU23KD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XAmqfwaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XAmqfwa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XAmqfwa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CardAPIController::api_deck_draw_process' => ['privates', '.service_locator.OBcHxWE', 'get_ServiceLocator_OBcHxWEService', true],
            'App\\Controller\\CardAPIController::api_deck_deal_process' => ['privates', '.service_locator.ksCDFaA', 'get_ServiceLocator_KsCDFaAService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CardAPIController:api_deck_draw_process' => ['privates', '.service_locator.OBcHxWE', 'get_ServiceLocator_OBcHxWEService', true],
            'App\\Controller\\CardAPIController:api_deck_deal_process' => ['privates', '.service_locator.ksCDFaA', 'get_ServiceLocator_KsCDFaAService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CardAPIController::api_deck_draw_process' => '?',
            'App\\Controller\\CardAPIController::api_deck_deal_process' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CardAPIController:api_deck_draw_process' => '?',
            'App\\Controller\\CardAPIController:api_deck_deal_process' => '?',
        ]);
    }
}
