<?php

namespace ContainerZJVYzqr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardAPIControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CardAPIController' shared autowired service.
     *
     * @return \App\Controller\CardAPIController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CardAPIController'] = $instance = new \App\Controller\CardAPIController(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\CardAPIController', $container));

        return $instance;
    }
}
