<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQLSlY7D\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQLSlY7D/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerQLSlY7D.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerQLSlY7D\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerQLSlY7D\App_KernelProdDebugContainer([
    'container.build_hash' => 'QLSlY7D',
    'container.build_id' => '7d931750',
    'container.build_time' => 1745445621,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQLSlY7D');
