<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZJVYzqr\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZJVYzqr/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZJVYzqr.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZJVYzqr\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZJVYzqr\App_KernelProdContainer([
    'container.build_hash' => 'ZJVYzqr',
    'container.build_id' => 'aa7ab022',
    'container.build_time' => 1745444936,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZJVYzqr');
