<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJAbHFcJ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJAbHFcJ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJAbHFcJ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJAbHFcJ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJAbHFcJ\App_KernelProdContainer([
    'container.build_hash' => 'JAbHFcJ',
    'container.build_id' => 'fd5e70d8',
    'container.build_time' => 1746927590,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJAbHFcJ');
