<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUnvKCJY\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUnvKCJY/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUnvKCJY.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUnvKCJY\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerUnvKCJY\App_KernelProdContainer([
    'container.build_hash' => 'UnvKCJY',
    'container.build_id' => 'de48752f',
    'container.build_time' => 1747932054,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUnvKCJY');
