<?php

namespace ContainerBr2Gohz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_LazyProfilerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.lazy_profiler' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Profiler\Profiler
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['.lazy_profiler'] = $container->createProxy('ProfilerProxy34e542e', static fn () => \ProfilerProxy34e542e::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->services['.container.private.profiler'] ?? self::get_Container_Private_ProfilerService($container));
    }
}
