<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM3YStqf\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM3YStqf/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerM3YStqf.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerM3YStqf\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerM3YStqf\App_KernelTestDebugContainer([
    'container.build_hash' => 'M3YStqf',
    'container.build_id' => 'd5a44f1f',
    'container.build_time' => 1746920443,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM3YStqf');
