<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLU0Oln2\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLU0Oln2/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLU0Oln2.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLU0Oln2\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLU0Oln2\App_KernelTestDebugContainer([
    'container.build_hash' => 'LU0Oln2',
    'container.build_id' => '242164da',
    'container.build_time' => 1746510135,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLU0Oln2');
