<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH4jpztu\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH4jpztu/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerH4jpztu.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerH4jpztu\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerH4jpztu\App_KernelTestDebugContainer([
    'container.build_hash' => 'H4jpztu',
    'container.build_id' => '70022a2c',
    'container.build_time' => 1746581229,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH4jpztu');
