<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqW0yI9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqW0yI9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIqW0yI9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIqW0yI9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIqW0yI9\App_KernelDevDebugContainer([
    'container.build_hash' => 'IqW0yI9',
    'container.build_id' => '66458265',
    'container.build_time' => 1747189458,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqW0yI9');
