<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYTk2vGr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYTk2vGr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYTk2vGr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYTk2vGr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYTk2vGr\App_KernelDevDebugContainer([
    'container.build_hash' => 'YTk2vGr',
    'container.build_id' => 'cf123b20',
    'container.build_time' => 1744601997,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYTk2vGr');
