<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS0hAyYo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS0hAyYo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS0hAyYo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS0hAyYo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS0hAyYo\App_KernelDevDebugContainer([
    'container.build_hash' => 'S0hAyYo',
    'container.build_id' => '33a1c347',
    'container.build_time' => 1747483948,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS0hAyYo');
