<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.971a7ffe.js',
                'build/app.c1705dca.js',
            ],
            'css' => [
                'build/app.2e5ba4f6.css',
            ],
        ],
    ],
],

]];
