<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.971a7ffe.js',
                'build/app.4c60af5a.js',
            ],
            'css' => [
                'build/app.cc39fe05.css',
            ],
        ],
        'project' => [
            'js' => [
                'build/runtime.971a7ffe.js',
                'build/project.50d16902.js',
            ],
            'css' => [
                'build/project.b344bcb4.css',
            ],
        ],
    ],
],

]];
